AWSTemplateFormatVersion: '2010-09-09'
Description: Simple AWS S3 Bucket
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: deployingonaws-bucket-478365823
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SimpleAWSTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

